"""
Sliding-window correlation engine for pattern detection.

Implements multi-event correlation patterns that detect suspicious behavior:
- Brute force: N failed logins from same source, then success
- Privilege escalation: normal user becomes admin
- Data exfiltration: large data transfer followed by account deletion
- Lateral movement: failed login attempts across multiple systems

Uses a time-sliding window to correlate events.
"""

from datetime import datetime, timedelta
from typing import List, Dict, Any, Callable, Optional
from dataclasses import dataclass
from collections import defaultdict


@dataclass
class CorrelationAlert:
    """Alert generated by correlation engine."""
    timestamp: datetime
    alert_type: str
    severity: str  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    description: str
    related_events: List[Dict[str, Any]]
    confidence: float  # 0.0 to 1.0


class EventWindow:
    """Time-based sliding window for events."""

    def __init__(self, window_size: timedelta):
        self.window_size = window_size
        self.events: List[Dict[str, Any]] = []

    def add(self, event: Dict[str, Any]):
        """Add event to window."""
        self.events.append(event)
        self._prune()

    def _prune(self):
        """Remove events outside window."""
        if not self.events:
            return

        # Convert string timestamps to datetime for comparison
        timestamps = []
        for e in self.events:
            ts = e['timestamp']
            if isinstance(ts, str):
                ts = datetime.fromisoformat(ts)
            timestamps.append(ts)

        if not timestamps:
            return

        latest = max(timestamps)
        cutoff = latest - self.window_size

        # Keep events within window
        filtered = []
        for e in self.events:
            ts = e['timestamp']
            if isinstance(ts, str):
                ts = datetime.fromisoformat(ts)
            if ts >= cutoff:
                filtered.append(e)

        self.events = filtered

    def get_events(self, source: Optional[str] = None, log_level: Optional[str] = None) -> List[Dict[str, Any]]:
        """Get events matching criteria."""
        results = self.events
        if source:
            results = [e for e in results if e.get('source') == source]
        if log_level:
            results = [e for e in results if e.get('log_level') == log_level]
        return results

    def clear(self):
        self.events.clear()


class CorrelationEngine:
    """Detects suspicious patterns in event streams."""

    def __init__(self, window_size_seconds: int = 300):
        self.window_size = timedelta(seconds=window_size_seconds)
        self.windows: Dict[str, EventWindow] = defaultdict(
            lambda: EventWindow(self.window_size)
        )
        self.alerts: List[CorrelationAlert] = []

    def add_event(self, event: Dict[str, Any]) -> Optional[CorrelationAlert]:
        """Process event and check for correlations."""
        source = event.get('source', 'unknown')
        window = self.windows[source]
        window.add(event)

        # Check all correlation rules
        alert = self._check_brute_force(event, window)
        if alert:
            self.alerts.append(alert)
            return alert

        alert = self._check_privilege_escalation(event, window)
        if alert:
            self.alerts.append(alert)
            return alert

        alert = self._check_lateral_movement(event, window)
        if alert:
            self.alerts.append(alert)
            return alert

        return None

    def _check_brute_force(self, event: Dict[str, Any], window: EventWindow) -> Optional[CorrelationAlert]:
        """
        Detect brute force: multiple failed login attempts from same source
        followed by successful login (or within suspicious timeframe).

        Pattern: N auth failures + 1 success (or suspicious behavior after)
        """
        message = event.get('message', '').lower()
        service = event.get('service', '').lower()
        source = event.get('source', '')

        # Trigger on successful login
        is_successful_login = (
            ('login' in service or 'auth' in service) and
            ('successful' in message or 'success' in message)
        )

        if is_successful_login:
            events = window.get_events(source=source)

            # Count recent failed logins
            failed_logins = []
            for e in events:
                e_msg = e.get('message', '').lower()
                e_service = e.get('service', '').lower()
                if ('login' in e_service or 'auth' in e_service) and ('failed' in e_msg or 'failure' in e_msg or 'denied' in e_msg or 'invalid' in e_msg):
                    failed_logins.append(e)

            # Brute force threshold: 3+ failed attempts then success
            if len(failed_logins) >= 3:
                return CorrelationAlert(
                    timestamp=datetime.now(),
                    alert_type='BRUTE_FORCE_ATTACK',
                    severity='HIGH',
                    description=f'Brute force detected: {len(failed_logins)} failed login attempts from {source} followed by success',
                    related_events=failed_logins + [event],
                    confidence=min(0.95, 0.7 + (len(failed_logins) * 0.1))
                )

        return None

    def _check_privilege_escalation(self, event: Dict[str, Any], window: EventWindow) -> Optional[CorrelationAlert]:
        """
        Detect privilege escalation: normal user gaining admin/root access.

        Pattern: User activity -> sudo/su attempt -> elevated service access
        """
        message = event.get('message', '').lower()
        log_level = event.get('log_level', '').upper()
        source = event.get('source', '')

        # Detect sudo/su attempts (allow both 'su' and 'su ' to catch various cases)
        is_privilege_attempt = (
            'sudo' in message or
            'su' in message or
            'elevation' in message or
            'privilege' in message
        )

        if is_privilege_attempt and log_level in ['WARN', 'ERROR']:
            events = window.get_events(source=source)

            # Check if there was normal user activity before this privilege attempt
            user_events = [e for e in events if e.get('log_level') not in ['WARN', 'ERROR', 'CRITICAL']]

            # Only alert if there was prior normal activity (indicates non-admin user)
            # and the privilege attempt failed or was suspicious
            if len(user_events) > 0:
                return CorrelationAlert(
                    timestamp=datetime.now(),
                    alert_type='PRIVILEGE_ESCALATION',
                    severity='CRITICAL',
                    description=f'Possible privilege escalation on {source}: privilege attempt after normal user activity',
                    related_events=user_events + [event],
                    confidence=0.8
                )

        return None

    def _check_lateral_movement(self, event: Dict[str, Any], window: EventWindow) -> Optional[CorrelationAlert]:
        """
        Detect lateral movement: failed login attempts across multiple systems.

        Pattern: Failed auth on multiple different hosts/services
        """
        message = event.get('message', '').lower()
        source = event.get('source', '')

        if 'failed' in message or 'denied' in message or 'unauthorized' in message:
            # Collect all failed auth events in window
            all_events = list(window.events)
            failed_events = [
                e for e in all_events
                if ('failed' in e.get('message', '').lower() or
                    'denied' in e.get('message', '').lower() or
                    'unauthorized' in e.get('message', '').lower())
            ]

            # Get unique targets (could be different services/hosts)
            unique_targets = set()
            for e in failed_events:
                target = e.get('fields', {}).get('target_host') or e.get('service')
                if target:
                    unique_targets.add(target)

            # Lateral movement: 3+ failed attempts across different targets
            if len(unique_targets) >= 3:
                return CorrelationAlert(
                    timestamp=datetime.now(),
                    alert_type='LATERAL_MOVEMENT',
                    severity='HIGH',
                    description=f'Lateral movement detected: failed login attempts across {len(unique_targets)} different systems',
                    related_events=failed_events,
                    confidence=min(0.9, 0.6 + (len(unique_targets) * 0.1))
                )

        return None

    def get_alerts(self) -> List[CorrelationAlert]:
        """Get all generated alerts."""
        return self.alerts

    def clear_alerts(self):
        """Clear alert history."""
        self.alerts.clear()

    def reset(self):
        """Reset all windows."""
        self.windows.clear()
        self.alerts.clear()
